version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: goproject 
      MYSQL_PASSWORD: goproject
      MYSQL_DATABASE: image_goproject
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(0.0.0.0:3306)
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    environment:
      API_PORT: "8080"
      MYSQL_USER: goproject
      MYSQL_PASSWORD: goproject
      MYSQL_DATABASE: image_goproject
      DB_HOST: tcp(db:3306)
    ports:
      - "8080:8080"
    # volumes:
    #   - ./:/go
    networks:
      - backend

networks:
  backend:
    driver: "bridge"